image: docker:20
services:
  - docker:20-dind

variables:
  TAG_NAME: "arm64"
  REGISTRY_IMAGE_NAME: "$CI_REGISTRY/zorgundostu/$CI_PROJECT_NAME:$TAG_NAME"

stages:
  - build
  - push

maven-build:
  image: maven:3.8.7-eclipse-temurin-17-alpine
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

docker-build:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker context create builder-context
    - docker buildx create --name builderx --driver docker-container --use builder-context
    - docker buildx build --tag "$REGISTRY_IMAGE_NAME" --push --platform=linux/arm64/v8 .
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
