image: docker:latest
services:
  - docker:dind

variables:
  TAG_NAME: "arm64"

stages:
  - build
  - push

maven-build:
  image: maven:3.8.7-eclipse-temurin-17-alpine
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

docker-build:
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --platform=linux/arm64/v8 --pull -t "$CI_REGISTRY_IMAGE:${TAG_NAME}" .
    - docker push "$CI_REGISTRY_IMAGE:${TAG_NAME}"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
