server:
  port: 8090

mp:
  datasource:
    location:
      jdbc-url: jdbc:postgresql://localhost:5432/zorgundostu
      username: postgres
      password: 123123a
      driver-class-name: org.postgresql.Driver
      configuration:
        maximum-pool-size: 30
