server:
  port: 8090
  servlet:
    context-path: /api/v1/locations

spring:
  main:
    banner-mode: "off"
  flyway:
    baselineOnMigrate: true

mp:
  datasource:
    location:
      jdbc-url: jdbc:postgresql://zorgundostu-db:5432/zorgundostu
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      configuration:
        maximum-pool-size: 30
