server:
  port: 8090

spring:
  main:
    banner-mode: "off"
  flyway:
    baselineOnMigrate: true

mp:
  datasource:
    location:
      jdbc-url: jdbc:postgresql://localhost:5432/zorgundostu
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      configuration:
        maximum-pool-size: 30
