server:
  port: 8080
  servlet:
    context-path: /api/mp-location/v1

spring:
  main:
    banner-mode: "off"
  flyway:
    baselineOnMigrate: true

mp:
  datasource:
    location:
      jdbc-url: jdbc:postgresql://zorgundostu-db:5432/zorgundostu
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      configuration:
        maximum-pool-size: 30

openapi:
  app:
    description: Location service for Zorgundostu project
    version: 1.0.0
    title: Zorgundostu API
    contact: Contact Support
    email: zorgundostu@gmail.com
    licence: Signy 1.0
    url: https://zorgundostu.com/
