
server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  main:
    banner-mode: "off"
  flyway:
    baselineOnMigrate: true

mp:
  datasource:
    location:
      jdbc-url: jdbc:postgresql://localhost:5432/zorgundostu
      username: postgres
      password: 123123a
      driver-class-name: org.postgresql.Driver
      configuration:
        maximum-pool-size: 30
